dotnet build src\Punfai.Report --configuration Debug
dotnet build src\Punfai.Report --configuration Release
dotnet build src\Punfai.Report.Ibex --configuration Debug
dotnet build src\Punfai.Report.Ibex --configuration Release
dotnet build src\Punfai.Report.IronScript --configuration Debug
dotnet build src\Punfai.Report.IronScript --configuration Release
dotnet build src\Punfai.Report.OfficeOpenXml --configuration Debug
dotnet build src\Punfai.Report.OfficeOpenXml --configuration Release
dotnet build src\Punfai.Report.Wpf --configuration Debug
dotnet build src\Punfai.Report.Wpf --configuration Release
